language: generic 
sudo: required
services: 
  - docker

# before tests are run
before_install:
  - docker build -t okwujeisrael/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true okwujeisrael/docker-react npm run test